# Generated by Django 5.2.9 on 2026-01-19 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('ecom', 'E-Commerce'), ('finished', 'Finished Goods')], default='ecom', max_length=20)),
                ('external_order_number', models.CharField(blank=True, help_text="Client's Order ID or PO Number", max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_address', models.TextField()),
                ('expected_dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('courier_name', models.CharField(blank=True, help_text='DHL, FedEx, or Trucking Co.', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outbound_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_requests', to='users.clientprofile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_requests', to='users.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('dispatched_quantity', models.PositiveIntegerField(default=0)),
                ('item_status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('missing', 'Missing'), ('damaged', 'Damaged')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outbound.outboundrequest')),
            ],
        ),
    ]
