# Generated by Django 5.2.9 on 2026-01-20 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='bin_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of small item bins', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fire_certificate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='insurance_policy_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pallet_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of pallets', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='storage_capacity_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total storage area in sq ft', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_code',
            field=models.CharField(blank=True, help_text='Unique identifier for the warehouse', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='working_days',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri', max_length=100, null=True),
        ),
    ]
