# Generated by Django 5.2.9 on 2026-01-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inboundRequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(blank=True, help_text='Electronic Product Code', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('unencoded', 'Un-encoded'), ('encoded', 'Encoded'), ('allocated', 'Allocated')], default='unencoded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbound_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tags', to='inboundRequests.inbounditem')),
            ],
        ),
    ]
