# Generated by Django 5.2.9 on 2025-12-31 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inboundRequests', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(help_text='Electronic Product Code', max_length=255, unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('batch_or_lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('encoded', 'Encoded'), ('allocated', 'Allocated')], default='encoded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who owns this inventory', on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tags', to='users.clientprofile')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfid_tags', to=settings.AUTH_USER_MODEL)),
                ('inbound_request', models.ForeignKey(help_text='The inbound request this tag was generated for', on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tags', to='inboundRequests.inboundrequest')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tags', to='users.warehouse')),
            ],
        ),
    ]
