# Generated by Django 5.2.9 on 2025-12-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidtag',
            name='created_by_user',
        ),
    ]
