# Generated by Django 5.2.9 on 2025-12-24 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('transport_mode', models.CharField(max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, help_text='Manager who approved this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inbound_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='users.clientprofile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='users.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('carton_weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=10)),
                ('carton_dimensions', models.CharField(help_text='L x W x H', max_length=100)),
                ('temperature_range', models.CharField(blank=True, max_length=50, null=True)),
                ('fragile', models.BooleanField(default=False)),
                ('hazardous', models.BooleanField(default=False)),
                ('humidity', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_type', models.CharField(choices=[('carton', 'Carton'), ('pallet', 'Pallet'), ('drum', 'Drum')], default='carton', max_length=20)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_arrival_date', models.DateField(help_text='Expected arrival date of the item')),
                ('item_status', models.CharField(choices=[('pending', 'Pending'), ('not arrived yet', 'Not Arrived Yet'), ('arrived', 'Arrived')], default='pending', max_length=20)),
                ('inbound_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inboundRequests.inboundrequest')),
            ],
        ),
    ]
