# Generated by Django 5.2.9 on 2026-01-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inboundRequests', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrequest',
            name='approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inbound_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='users.clientprofile'),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='users.warehouse'),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='inbound_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inboundRequests.inboundrequest'),
        ),
    ]
