# Generated by Django 5.2.9 on 2026-01-02 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboundRequests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundrequest',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='expected_arrival_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Expected arrival for this specific item'),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='hazardous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='humidity_range',
            field=models.CharField(blank=True, help_text="e.g., '40-60%'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='temp_range',
            field=models.CharField(blank=True, help_text="e.g., '10-20 C'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='total_inventory_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value in currency', max_digits=15),
        ),
        migrations.AddField(
            model_name='inbounditem',
            name='unit_type',
            field=models.CharField(choices=[('carton', 'Carton'), ('pallet', 'Pallet'), ('piece', 'Piece'), ('drum', 'Drum')], default='carton', max_length=20),
        ),
    ]
