# Generated by Django 5.2.9 on 2026-01-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboundRequests', '0003_remove_inboundrequest_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbounditem',
            name='item_status',
            field=models.CharField(choices=[('not arrived yet', 'Not Arrived Yet'), ('arrived', 'Arrived')], default='not arrived yet', max_length=30),
        ),
    ]
