# Generated by Django 5.2.9 on 2026-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboundRequests', '0004_alter_inbounditem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounditem',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
