# Generated by Django 5.2.9 on 2026-01-19 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('request_id', models.PositiveIntegerField(help_text='ID of the related Inbound or Outbound Request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_user', models.ForeignKey(help_text='Manager who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_allocator', models.ForeignKey(blank=True, help_text='Allocator assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocator_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_deo', models.ForeignKey(blank=True, help_text='DEO assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deo_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
