# Generated by Django 5.2.9 on 2026-01-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inboundRequests', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by_user',
            field=models.ForeignKey(help_text='Manager who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_user',
            field=models.ForeignKey(help_text='DEO or Allocator assigned to the task', on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='inbound_request',
            field=models.ForeignKey(blank=True, help_text='The Inbound Request this task is related to (if type is Inbound)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inboundRequests.inboundrequest'),
        ),
    ]
