# Generated by Django 5.2.9 on 2026-01-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discrepancy', '0001_initial'),
        ('inboundRequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancy',
            name='inbound_item',
            field=models.ForeignKey(help_text='The item where discrepancy was found', on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inboundRequests.inbounditem'),
        ),
    ]
