# Generated by Django 5.2.9 on 2026-01-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Max weight in KG', max_digits=10)),
                ('epc', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('FLOOR', 'Floor'), ('PALLET', 'Pallet Position'), ('SHELF', 'Shelf'), ('BIN', 'Bin'), ('COLD', 'Cold Storage'), ('HAZMAT', 'Hazmat')], max_length=20)),
                ('allowed_client_type', models.CharField(choices=[('ECOM', 'E-Commerce'), ('FINISHED', 'Finished Goods'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('min_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hazard_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_units', models.PositiveIntegerField()),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Max weight in KG', max_digits=10)),
                ('epc', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='locations.level')),
            ],
        ),
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('epc', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rack_type', models.CharField(choices=[('PALLET', 'Pallet Rack'), ('SHELF', 'Shelving Unit')], max_length=20)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Max weight in KG', max_digits=10)),
                ('epc', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='locations.aisle')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='locations.rack'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('STORAGE', 'Storage'), ('PICK', 'Pick'), ('COLD', 'Cold Storage'), ('HAZMAT', 'Hazardous Materials'), ('DISPATCH', 'Dispatch')], max_length=20)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='users.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.zone'),
        ),
    ]
