# Generated by Django 5.2.9 on 2026-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('FLOOR', 'Floor'), ('PALLET', 'Pallet'), ('SHELF', 'Shelf'), ('BIN', 'Bin'), ('COLD', 'Cold Storage'), ('HAZMAT', 'Hazmat')], max_length=20),
        ),
    ]
