# Generated by Django 5.2.9 on 2026-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='allowed_client_type',
        ),
        migrations.AddField(
            model_name='aisle',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('PARTIAL', 'Partially Filled'), ('FULL', 'Full')], default='EMPTY', max_length=20),
        ),
        migrations.AddField(
            model_name='bin',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('PARTIAL', 'Partially Filled'), ('FULL', 'Full')], default='EMPTY', max_length=20),
        ),
        migrations.AddField(
            model_name='level',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('PARTIAL', 'Partially Filled'), ('FULL', 'Full')], default='EMPTY', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('PARTIAL', 'Partially Filled'), ('FULL', 'Full')], default='EMPTY', max_length=20),
        ),
        migrations.AddField(
            model_name='rack',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('PARTIAL', 'Partially Filled'), ('FULL', 'Full')], default='EMPTY', max_length=20),
        ),
    ]
